### ISSUE TITLE
Initialization of factors random?

### ISSUE THREAD

**Issue by ViriatoII** [bioFAM/FISHFactor#1]
Hello,

Your paper is very interesting. I'm trying to apply it and it appears to me that you initialize the factors randomly and iteratively try to improve them to fit the training data. 

My question is: Why not initialize one of the factors non-randomly? There is one obvious pattern that is common in cells, a distribution that fades with the distance to the centre of the cell.  

I was just wondering if this would make your algorithm faster to compute. I would love to reach thousands of cells with reasonable computation resources. 

Maybe also for this purpose, is it possible to use a coarser resolution? - EDIT: I already see that is possible.

Kind regards,
Ricardo

**Comment by florinwalter** [comment]
Hi Ricardo,

thanks a lot for the comment! I agree that the latent variables' initialization is somewhat random at the moment and that doing this differently could further improve the method (I'm particularly thinking about the weights).

I guess you're referring to Fig. 5a in the paper, where one factor captures the nucleus in the center of the cell. If something like this is expected, it could indeed make sense to explicitly account for that in the model. But for the more general case I think that the method should be able to detect any smooth patterns, without being constrained or having a very strong prior for a specific factor shape.

The available levers for making the method faster currently are the number of inducing points (reduce them), the grid points of the likelihood integral (reduce them) and the maximum number of data points / batch size (reduce them). But as almost always, this comes at the cost of possibly worse results :)

Regards,
Florin

**Comment by ViriatoII** [comment]
Thank you for the answer! Keep up the great work!
