### ISSUE TITLE
Torch error

### ISSUE THREAD

**Issue by ViriatoII** [bioFAM/FISHFactor#2]
Hi again,

Just as a note, I get a torch error when running FISHFactor with many cells (>100). It happens seemingly at a random epoch, after several epochs have worked well. It seems that it hits a point where all cell weights are invalid (?).

Maybe this happens because there are no consistent patterns in my input, I notice that if I run this with only 15 cells, it runs for 5000 epochs but reaches completely different results on different runs. And the "min loss"  values of the cells do not change after the first 5-50 epochs.

This is the error:

>ValueError                                Traceback (most recent call last)`

>/usr/local/lib/python3.7/dist-packages/pyro/poutine/trace_messenger.py in __call__(self, *args, **kwargs)
    173             try:
--> 174                 ret = self.fn(*args, **kwargs)
    175             except (ValueError, RuntimeError) as e:

> -----------------24 frames <> -------------------------------------------
ValueError: Expected parameter loc (Tensor of shape (3, 3620)) of distribution Normal(loc: torch.Size([3, 3620]), scale: torch.Size([3, 3620])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddBackward0>)

>The above exception was the direct cause of the following exception:
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/torch/distributions/distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     54                 if not valid.all():
     55                     raise ValueError(
---> 56                         f"Expected parameter {param} "
     57                         f"({type(value).__name__} of shape {tuple(value.shape)}) "
     58                         f"of distribution {repr(self)} "

>ValueError: Expected parameter loc (Tensor of shape (3, 3620)) of distribution Normal(loc: torch.Size([3, 3620]), scale: torch.Size([3, 3620])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddBackward0>)
Trace Shapes:                      
 Param Sites:                      
    w_loc_raw       39 1  3 1      
  w_scale_raw       39 1  3 1      
Sample Sites:                      
 K_plate dist               |      
        value             3 |      
 M_plate dist               |      
        value             1 |      
 D_plate dist               |      
        value            39 |      
       w dist 15 39  1 3  1 |      
        value 15 39  1 3  1 |      
      .u dist 15  1  1 3  1 | 3 400
        value 15  1  1 3  1 | 3 400`

**Comment by florinwalter** [comment]
Hi!
That looks like something is not right, even with data that does not have obvious patterns in it I would expect the loss to decrease for more than just the first 5-50 epochs...
Can you say a bit more about the data? Did you arrange it in a DataFrame like it is shown in the example.ipynb file? How many data points does the data have per feature/gene?
