### ISSUE TITLE
NVIDIA graphics card needed

### ISSUE THREAD

**Issue by sthawinke** [bioFAM/FISHFactor#3]
Hello,

First of all great work on the package, you are really making most of the images' resolutions. After a long struggle a realized that I cannot run the package as I have an Intel graphics card rather than NVIDIA. Are you planning to extend the code to other graphics card too? On top of that, it may be good to flag this issue in the man pages to save others the trouble.

Cheers,

Stijn

**Comment by florinwalter** [comment]
Hi Stijn,

thanks for reaching out. The model implementation is based on PyTorch, which to my knowledge does not work with Intel graphics cards unfortunately. If you don't have an NVIDIA card available I'm afraid you need to use your cpu (`device='cpu'`), which is a lot slower of course but should still work.

Best,
Florin

**Comment by sthawinke** [comment]
Hi Florin,

Ok thanks for that!

Stijn
